### PR TITLE
added dice

### PR DESCRIPTION
**Pull request by everyonce**

### CODE REVIEW

**Comment by Retzy** [comment]
This has more features (and more room to fix bugs) than the Slack-included one. Do we want to add this in or keep the Slack add-in?

**Comment by lydonb** [comment]
I say we just keep the slack add-in as it's not getting much use anyway

**Comment by everyonce** [comment]
I added this because we were running out of slack integrations for our free plan

**Comment by lydonb** [comment]
Cool, sounds reasonable to me. I'm not against it.

**Pull request merged**
